name: Run Pytest

on: 
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:
  workflow_call:
jobs:
  deploy:
    name: Deploy to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install build dependencies
        run: python -m pip install build twine

      - name: Build distributions
        run: python -m build

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TWINE_PASSWORD}}